- pom.xml
- src/main/java/de/unistuttgart/iaas/amyassist/amy/core/di/ClassIsNotAServiceException.java
- src/main/java/de/unistuttgart/iaas/amyassist/amy/core/di/DependencyInjection.java
- src/main/java/de/unistuttgart/iaas/amyassist/amy/core/di/DuplicateServiceException.java
- src/main/java/de/unistuttgart/iaas/amyassist/amy/core/di/ServiceNotFoundException.java
- src/main/java/de/unistuttgart/iaas/amyassist/amy/core/di/annotation/Reference.java
- src/main/java/de/unistuttgart/iaas/amyassist/amy/core/di/annotation/Service.java
- src/main/java/de/unistuttgart/iaas/amyassist/amy/plugin/example/HelloWorldLogic.java
- src/main/java/de/unistuttgart/iaas/amyassist/amy/plugin/example/HelloWorldSpeech.java
- src/test/java/de/unistuttgart/iaas/amyassist/amy/FramworkExtention.java
- src/test/java/de/unistuttgart/iaas/amyassist/amy/TestFramework.java
- src/test/java/de/unistuttgart/iaas/amyassist/amy/core/di/DependencyInjectionTest.java
- src/test/java/de/unistuttgart/iaas/amyassist/amy/core/di/Service1.java
- src/test/java/de/unistuttgart/iaas/amyassist/amy/core/di/Service2.java
- src/test/java/de/unistuttgart/iaas/amyassist/amy/core/di/Service3.java
- src/test/java/de/unistuttgart/iaas/amyassist/amy/core/di/Service4.java
- src/test/java/de/unistuttgart/iaas/amyassist/amy/core/di/Service5.java
- src/test/java/de/unistuttgart/iaas/amyassist/amy/plugin/example/HelloWorldTest.java
added Dependency Injection
added Annotation @Service and @Reference
> Dependency Injection

- pom.xml
- src/main/java/de/unistuttgart/iaas/amyassist/amy/plugin/weather/WeatherDarkSkyAPI.java
- src/main/java/de/unistuttgart/iaas/amyassist/amy/plugin/weather/WeatherSpeechCommand.java
> Add basic weather plugin

- plugins/systemtime/src/main/java/de/unistuttgart/iaas/amyassist/amy/plugin/systemtime/SystemTimeSpeech.java
Improvement of Amy Feedback on current time
> improved time output for tts

- plugins/example/src/test/java/de/unistuttgart/iaas/amyassist/amy/plugin/example/HelloWorldRestTest.java
- plugins/example/src/test/java/de/unistuttgart/iaas/amyassist/amy/plugin/example/HelloWorldTest.java
- testing-framework/src/main/java/de/unistuttgart/iaas/amyassist/amy/test/FrameworkExtension.java
- testing-framework/src/main/java/de/unistuttgart/iaas/amyassist/amy/test/LoggerProvider.java
- testing-framework/src/main/java/de/unistuttgart/iaas/amyassist/amy/test/Storage.java
- testing-framework/src/main/java/de/unistuttgart/iaas/amyassist/amy/test/TestFramework.java
- testing-framework/src/main/java/de/unistuttgart/iaas/amyassist/amy/test/TestFrameworkImpl.java
> extraced simple interface of the testframework

- api/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/IPlugin.java
- core/pom.xml
- core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/pluginloader/Plugin.java
- core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/pluginloader/PluginLoader.java
- core/src/test/java/de/unistuttgart/iaas/amyassist/amy/core/pluginloader/PluginTest.java
- plugins/pom.xml
... to be the maven groupId plus the maven artifactId. Additionaly adds plugin.displayName.
> Changes plugin.uniqueName

- api/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/Configuration.java
- api/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/IPlugin.java
- core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/ConfigurationImpl.java
- core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/pluginloader/Plugin.java
- core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/pluginloader/PluginManagerCLI.java
- plugins/pom.xml
Uses the mvn poms description.
> Adds description to plugin objects.

- core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/configuration/ConfigurationLoader.java
- core/src/test/java/de/unistuttgart/iaas/amyassist/amy/core/configuration/ConfigurationLoaderTest.java
- di-api/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/di/annotation/PreDestroy.java
- di/src/test/java/de/unistuttgart/iaas/amyassist/amy/core/di/DependencyInjectionScopeTest.java
added tests for ConfigurationLoader
added PreDestroy Annotation(api only)
> added store method to ConfigurationLoader

- plugins/spotify/src/main/java/de/unistuttgart/iaas/amyassist/amy/plugin/spotify/MusicResource.java
- plugins/spotify/src/main/java/de/unistuttgart/iaas/amyassist/amy/plugin/spotify/SpotifyAPICalls.java
- plugins/spotify/src/main/java/de/unistuttgart/iaas/amyassist/amy/plugin/spotify/SpotifyConstants.java
- plugins/spotify/src/main/java/de/unistuttgart/iaas/amyassist/amy/plugin/spotify/SpotifySpeech.java
- plugins/spotify/src/test/java/de/unistuttgart/iaas/amyassist/amy/plugin/spotify/MusicRestTest.java
- plugins/spotify/src/test/java/de/unistuttgart/iaas/amyassist/amy/plugin/spotify/SpotifyAPICallsTest.java
Rest Bugfix in CurrentSong and in the token creation
> Rest bugfixing spotify

- api/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/plugin/api/registry/Location.java
- api/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/plugin/api/registry/RegistryException.java
- core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/registry/AbstractRegistry.java
- core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/registry/location/LocationImpl.java
- core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/registry/location/LocationRegistryImpl.java
- plugins/example/src/main/java/de/unistuttgart/iaas/amyassist/amy/plugin/example/HelloWorldImpl.java
Add `name` attribute to Location of LocationRegistry.
> Registry: Add `name` attribute to location. More tests.

- plugins/weather/src/main/java/de/unistuttgart/iaas/amyassist/amy/plugin/weather/WeatherDarkSkyAPI.java
the weather plugin now saves its forecast for an hour or until the next day, to reduce calls to the api
> Improvement to the weather plugin

- api/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/io/Environment.java
- core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/io/EnvironmentService.java
new feature:
- the environment now provides the current LocalDateTime and ZonedDateTime
> added LocalDateTime and ZonedDateTime to the Environment

- plugins/systemtime/src/main/java/de/unistuttgart/iaas/amyassist/amy/plugin/systemtime/SystemTimeLogic.java
- plugins/systemtime/src/main/java/de/unistuttgart/iaas/amyassist/amy/plugin/systemtime/SystemTimeResource.java
- plugins/systemtime/src/main/java/de/unistuttgart/iaas/amyassist/amy/plugin/systemtime/SystemTimeSpeech.java
- plugins/systemtime/src/test/java/de/unistuttgart/iaas/amyassist/amy/plugin/systemtime/SystemTimeLogicTest.java
changed SystemTime to use the Environment time #192.
> SystemTime refactor

- core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/Core.java
- core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/CoreServiceProviderLoader.java
- registry/pom.xml
- registry/src/main/java/de/unistuttgart/iaas/amyassist/amy/registry/AbstractRegistry.java
- registry/src/main/java/de/unistuttgart/iaas/amyassist/amy/registry/ContactImpl.java
- registry/src/main/java/de/unistuttgart/iaas/amyassist/amy/registry/ContactRegistryImpl.java
- registry/src/main/java/de/unistuttgart/iaas/amyassist/amy/registry/LocationImpl.java
- registry/src/main/java/de/unistuttgart/iaas/amyassist/amy/registry/LocationRegistryImpl.java
- registry/src/main/java/de/unistuttgart/iaas/amyassist/amy/registry/rest/AbstractRegistryResource.java
- registry/src/main/java/de/unistuttgart/iaas/amyassist/amy/registry/rest/ContactRegistryResource.java
- registry/src/main/java/de/unistuttgart/iaas/amyassist/amy/registry/rest/LocationRegistryResource.java
> Registry REST

- http-server/pom.xml
- http-server/src/main/java/de/unistuttgart/iaas/amyassist/amy/httpserver/Server.java
- pom.xml
- testing-framework/src/main/java/de/unistuttgart/iaas/amyassist/amy/test/TestFrameworkImpl.java
> added swagger integration

- plugins/calendar/pom.xml
- plugins/calendar/src/main/java/de/unistuttgart/iaas/amyassist/amy/plugin/calendar/CalendarResource.java
- plugins/calendar/src/test/java/de/unistuttgart/iaas/amyassist/amy/plugin/calendar/CalendarRestTest.java
Added REST Resource and Tests for calendar
> REST for Calendar

- plugins/navigation/src/main/java/de/unistuttgart/iaas/amyassist/amy/plugin/navigation/NavigationResource.java
- plugins/navigation/src/main/java/de/unistuttgart/iaas/amyassist/amy/plugin/navigation/rest/Route.java
- plugins/navigation/src/test/java/de/unistuttgart/iaas/amyassist/amy/plugin/navigation/NavigationRestTest.java
changed navigation resource to have a more natural usage
> Navigation resource

- plugins/alarmclock/src/main/java/de/unistuttgart/iaas/amyassist/amy/plugin/alarmclock/AlarmClockLogic.java
- plugins/alarmclock/src/test/java/de/unistuttgart/iaas/amyassist/amy/plugin/alarmclock/AlarmClockLogicTest.java
> Fixed delete alarm/timer bug

- core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/Core.java
- core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/CoreServiceProviderLoader.java
- core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/console/Console.java
- core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/pluginloader/PluginManagerService.java
- core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/service/RunnableService.java
- core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/service/ServiceManagerImpl.java
- core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/speech/LocalAudioUserInteraction.java
- core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/speech/tts/TextToSpeech.java
- core/src/main/resources/META-INF/de.unistuttgart.iaas.amyassist.amy.core.service.RunnableService
- core/src/test/java/de/unistuttgart/iaas/amyassist/amy/core/service/ServiceManagerImplTest.java
- core/src/test/java/de/unistuttgart/iaas/amyassist/amy/core/service/TestRunnableService.java
- core/src/test/resources/META-INF/de.unistuttgart.iaas.amyassist.amy.core.service.RunnableService
added new RunnableService  and the manager to start and stop services #199
fixed #186
close #199
> added RunnableService interface

- plugins/weather/src/main/java/de/unistuttgart/iaas/amyassist/amy/plugin/weather/WeatherReportDay.java
- plugins/weather/src/test/java/de/unistuttgart/iaas/amyassist/amy/plugin/weather/WeatherRestTest.java
> WeatherPlugin: Add `icon` attribute to weather reports

- plugins/alarmclock/src/main/java/de/unistuttgart/iaas/amyassist/amy/plugin/alarmclock/Alarm.java
- plugins/alarmclock/src/main/java/de/unistuttgart/iaas/amyassist/amy/plugin/alarmclock/AlarmClockLogic.java
- plugins/alarmclock/src/main/java/de/unistuttgart/iaas/amyassist/amy/plugin/alarmclock/AlarmClockSpeech.java
- plugins/alarmclock/src/main/java/de/unistuttgart/iaas/amyassist/amy/plugin/alarmclock/rest/Timestamp.java
- plugins/alarmclock/src/test/java/de/unistuttgart/iaas/amyassist/amy/plugin/alarmclock/AlarmClockLogicTest.java
- plugins/alarmclock/src/test/java/de/unistuttgart/iaas/amyassist/amy/plugin/alarmclock/AlarmTest.java
> replaced Calendar with LocalTime to better fit requirements

- core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/speech/recognizer/SpeechRecognizer.java
- core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/speech/recognizer/handler/AbstractRecognitionResultHandler.java
bugfix and new logger.debug output
#194 
#193 
> fixed bug and added logger.debug of recognnitionresult

- plugins/weather/src/main/java/de/unistuttgart/iaas/amyassist/amy/plugin/weather/WeatherDarkSkyAPI.java
NullPointer by deleting the weather location is now fixed with this pr
> Bugfix Weather Plugin

- plugins/spotify/src/main/java/de/unistuttgart/iaas/amyassist/amy/plugin/spotify/MusicResource.java
- plugins/spotify/src/main/java/de/unistuttgart/iaas/amyassist/amy/plugin/spotify/SpotifyAPICalls.java
- plugins/spotify/src/main/java/de/unistuttgart/iaas/amyassist/amy/plugin/spotify/SpotifySpeech.java
- plugins/spotify/src/main/java/de/unistuttgart/iaas/amyassist/amy/plugin/spotify/logic/DeviceLogic.java
- plugins/spotify/src/main/java/de/unistuttgart/iaas/amyassist/amy/plugin/spotify/logic/PlayerLogic.java
- plugins/spotify/src/test/java/de/unistuttgart/iaas/amyassist/amy/plugin/spotify/SpotifyAPICallsTest.java
Serval improvements and fixes are in this pr
- fix serveral rest interfaces
- getVolume has now a rest interface
- longer speech command to prevent worng recognition
- refresh token is now in the storage an not in the config file
> Spotify improvments

- core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/speech/recognizer/handler/AbstractRecognitionResultHandler.java
description (is this a bugfix, change or a new feature)
add links to issues
> fixed bug that amy hears herself

- plugins/spotify/src/main/java/de/unistuttgart/iaas/amyassist/amy/plugin/spotify/SpotifySpeech.java
Fix for speech command setVolume in the spotify plugin
> fix for speech comand setVolume

- registry/src/main/java/de/unistuttgart/iaas/amyassist/amy/registry/LocationRegistryImpl.java
- registry/src/main/java/de/unistuttgart/iaas/amyassist/amy/registry/RegistryInvalidRequestException.java
- registry/src/main/java/de/unistuttgart/iaas/amyassist/amy/registry/rest/AbstractRegistryResource.java
> AbstractRegistryResource: Handle errors better

- plugins/alarmclock/src/main/java/de/unistuttgart/iaas/amyassist/amy/plugin/alarmclock/AlarmClockSpeech.java
- plugins/navigation/src/main/java/de/unistuttgart/iaas/amyassist/amy/plugin/navigation/NavigationSpeech.java
- plugins/navigation/src/main/java/de/unistuttgart/iaas/amyassist/amy/plugin/navigation/TimeFormatter.java
New grammar for time to process the new input from the web ui from the google speech
> changes for google speech in grammars from navigation and alarmclock

- plugins/calendar/pom.xml
- plugins/calendar/src/main/java/de/unistuttgart/iaas/amyassist/amy/plugin/calendar/CalendarEvent.java
description (is this a bugfix, change or a new feature)
add links to issues
> adds XmlJavaTypeAdapter to the LocalDateTime start and end

- config/server.config.properties
- http-server/src/main/java/de/unistuttgart/iaas/amyassist/amy/httpserver/Server.java
- http-server/src/test/java/de/unistuttgart/iaas/amyassist/amy/httpserver/ServerTest.java
- testing-framework/src/main/java/de/unistuttgart/iaas/amyassist/amy/test/TestFrameworkImpl.java
make it possible to use swagger ui to test the rest resources
added [Wiki](https://github.com/AmyAssist/Amy/wiki/HTTP-Server)
> added Server to OpenAPI

- plugins/email/src/main/java/de/unistuttgart/iaas/amyassist/amy/plugin/email/EMailResource.java
- plugins/email/src/test/java/de/unistuttgart/iaas/amyassist/amy/plugin/email/EMailRestTest.java
> Changed return value when no important mails were found

- http-server/src/main/java/de/unistuttgart/iaas/amyassist/amy/httpserver/Server.java
> fixed OpenApi reflections warning

- core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/natlang/JSGFGenerator.java
numbers from 0 to 99 can now recognize well. but numbers over 100 can not recognize now
> Fix for number regocnition

- di/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/di/DependencyInjection.java
- di/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/di/provider/SingletonServiceProvider.java
Fixes a little typo in the class name of the Dependency Injection
closes #242 
> Fixed typo in DI class

- core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/speech/recognizer/manager/AbstractSpeechRecognizerManager.java
> log what amy speech recognition understood

- PULL_REQUEST_TEMPLATE.md
added Code conventions to pull request template
> added coverage to pull request template

- core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/CoreServiceProviderLoader.java
- core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/di/Services.java
- core/src/main/resources/META-INF/de.unistuttgart.iaas.amyassist.amy.core.di.Services
- di/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/di/DependencyInjection.java
- di/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/di/DuplicateServiceException.java
- http-server/.classpath
- http-server/src/main/resources/META-INF/de.unistuttgart.iaas.amyassist.amy.core.di.Services
- registry/.classpath
- registry/src/main/resources/META-INF/de.unistuttgart.iaas.amyassist.amy.core.di.Services
https://github.com/AmyAssist/Amy/wiki/Core
> Use deployment descriptor files for Services in the main jar close #315

- di/pom.xml
- pom.xml
- registry/pom.xml
- registry/src/main/java/de/unistuttgart/iaas/amyassist/amy/registry/LocationRegistryImpl.java
- registry/src/main/java/de/unistuttgart/iaas/amyassist/amy/registry/geocoder/Geocoder.java
> fixed access restriction

- core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/configuration/PropertiesProvider.java
- core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/logger/LoggerProvider.java
- di-api/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/di/Configuration.java
- di-api/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/di/ContextLocator.java
- di-api/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/di/ServiceLocator.java
- di-api/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/di/SimpleServiceLocator.java
- di-api/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/di/provider/ServiceProvider.java
- di/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/di/ContextLocatorImpl.java
- di/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/di/DependencyInjection.java
- di/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/di/ServiceCreation.java
- di/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/di/SimpleServiceLocatorImpl.java
- di/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/di/provider/ClassServiceProvider.java
- di/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/di/provider/SingletonServiceProvider.java
- di/src/test/java/de/unistuttgart/iaas/amyassist/amy/core/di/DependencyInjectionTest.java
- testing-framework/src/main/java/de/unistuttgart/iaas/amyassist/amy/test/LoggerProvider.java
fixed circular dependencies detection
fixed multiple threads creating services
> Di multithread support

- api/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/configuration/EnvironmentConfigurationLoader.java
- api/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/io/Environment.java
- core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/configuration/ConfigurationManagerImpl.java
- core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/configuration/EnvironmentConfigurationLoaderImpl.java
- core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/io/EnvironmentService.java
- core/src/test/java/de/unistuttgart/iaas/amyassist/amy/core/configuration/EnvironmentConfigurationLoaderTest.java
Adds a configuration loader that can read from the environment variables.
Needed for #331.
> Add environment configuration loader.

- api/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/configuration/EnvironmentConfigurationLoader.java
- core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/configuration/EnvironmentConfigurationLoaderImpl.java
- core/src/main/resources/META-INF/de.unistuttgart.iaas.amyassist.amy.core.di.Services
- core/src/test/java/de/unistuttgart/iaas/amyassist/amy/core/configuration/EnvironmentConfigurationLoaderTest.java
Second try of #333 because the first one had a major bug.
> Environment config

- core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/persistence/PersistenceService.java
> workaround for Hibernate wrong Properties usage

- .travis.yml
> added system tests via docker run

- .travis.yml
> added travis_retry to install step

- core/pom.xml
- pom.xml
> changed sphinx4 groupId and repository, but the artefact is the same

- amy-master-node/pom.xml
- plugins/pom.xml
- pom.xml
Upgrade some pretty old maven plugins
> Update maven plugins

- .settings/org.eclipse.jdt.core.prefs
- amy-master-node/.settings/org.eclipse.jdt.core.prefs
- amy-message-hub-api/.settings/org.eclipse.jdt.core.prefs
- amy-message-hub/.settings/org.eclipse.jdt.core.prefs
- api/.settings/org.eclipse.jdt.core.prefs
- core/.settings/org.eclipse.jdt.core.prefs
- deployment-descriptor-utility/.settings/org.eclipse.jdt.core.prefs
- di-api/.settings/org.eclipse.jdt.core.prefs
- di/.settings/org.eclipse.jdt.core.prefs
- http-server/.settings/org.eclipse.jdt.core.prefs
- plugin-manager-api/.settings/org.eclipse.jdt.core.prefs
- plugins/alarmclock/.settings/org.eclipse.jdt.core.prefs
- plugins/calendar/.settings/org.eclipse.jdt.core.prefs
- plugins/email/.settings/org.eclipse.jdt.core.prefs
- plugins/example/.settings/org.eclipse.jdt.core.prefs
- plugins/navigation/.settings/org.eclipse.jdt.core.prefs
- plugins/spotify/.settings/org.eclipse.jdt.core.prefs
- plugins/systemtime/.settings/org.eclipse.jdt.core.prefs
- plugins/weather/.settings/org.eclipse.jdt.core.prefs
- registry/.settings/org.eclipse.jdt.core.prefs
- rest-resources/.settings/org.eclipse.jdt.core.prefs
- testing-framework/.settings/org.eclipse.jdt.core.prefs
- utility/.settings/org.eclipse.jdt.core.prefs
this fixes the error in eclipse in the Search class
> changed eclipse jdt annotations to javax annotations

- rest-resources/pom.xml
- rest-resources/src/main/java/de/unistuttgart/iaas/amyassist/amy/restresources/home/HomeResource.java
- rest-resources/src/test/java/de/unistuttgart/iaas/amyassist/amy/restresources/home/HomeResourceTest.java
It's now posible to mute and unmute amy via REST.
> Support for mute / unmute via REST (part of #294)

- plugins/email/src/main/java/de/unistuttgart/iaas/amyassist/amy/plugin/email/EMailLogic.java
- plugins/email/src/main/java/de/unistuttgart/iaas/amyassist/amy/plugin/email/rest/EMailResource.java
- plugins/email/src/main/java/de/unistuttgart/iaas/amyassist/amy/plugin/email/session/GMailSession.java
- plugins/email/src/test/java/de/unistuttgart/iaas/amyassist/amy/plugin/email/EMailRestTest.java
- plugins/email/src/test/java/de/unistuttgart/iaas/amyassist/amy/plugin/email/EmailLogicTest.java
Code quality/runtime improvement
> Logic now only gets the amount of mails that is really needed

- plugins/calendar/src/test/java/de/unistuttgart/iaas/amyassist/amy/plugin/calendar/CalendarRestTest.java
- plugins/email/src/test/java/de/unistuttgart/iaas/amyassist/amy/plugin/email/EMailRestTest.java
- plugins/example/src/test/java/de/unistuttgart/iaas/amyassist/amy/plugin/example/HelloWorldRestTest.java
- plugins/navigation/src/test/java/de/unistuttgart/iaas/amyassist/amy/plugin/navigation/NavigationRestTest.java
- plugins/spotify/src/test/java/de/unistuttgart/iaas/amyassist/amy/plugin/spotify/MusicRestTest.java
- plugins/systemtime/src/main/java/de/unistuttgart/iaas/amyassist/amy/plugin/systemtime/SystemTimeResource.java
- plugins/systemtime/src/test/java/de/unistuttgart/iaas/amyassist/amy/plugin/systemtime/SystemTimeRestTest.java
- plugins/weather/src/test/java/de/unistuttgart/iaas/amyassist/amy/plugin/weather/WeatherRestTest.java
1. Fixed about 150 warnings and improved code from RestTests
2. Added new REST Methods for SystemTime
> RestTestImprovement

- http-server/src/main/java/de/unistuttgart/iaas/amyassist/amy/httpserver/ThrowableExceptionMapper.java
> fixed sonarcloud issues

- core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/console/ConsoleImpl.java
> fixed errors not printed with the logger

- plugins/alarmclock/src/main/java/de/unistuttgart/iaas/amyassist/amy/plugin/alarmclock/AlarmClockLogic.java
this is only a little fix to set a unique alarm Id
> fixing alarmId

- plugins/calendar/src/main/java/de/unistuttgart/iaas/amyassist/amy/plugin/calendar/CalendarResource.java
- plugins/calendar/src/test/java/de/unistuttgart/iaas/amyassist/amy/plugin/calendar/CalendarRestTest.java
Changing the backend for WebApp needs.
> Refactor Calendar Plugin

- amy-message-hub-api/src/main/java/de/unistuttgart/iaas/amyassist/amy/messagehub/topics/LocationTopics.java
- amy-message-hub-api/src/main/java/de/unistuttgart/iaas/amyassist/amy/messagehub/topics/RoomTopics.java
- amy-message-hub-api/src/main/java/de/unistuttgart/iaas/amyassist/amy/messagehub/topics/SmarthomeFunctionTopics.java
- amy-message-hub-api/src/main/java/de/unistuttgart/iaas/amyassist/amy/messagehub/topics/SystemTopics.java
- core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/speech/recognizer/manager/AbstractSpeechRecognizerManager.java
- plugins/alarmclock/src/main/java/de/unistuttgart/iaas/amyassist/amy/plugin/alarmclock/AlarmBeepService.java
- plugins/spotify/src/main/java/de/unistuttgart/iaas/amyassist/amy/plugin/spotify/logic/PlayerLogic.java
- rest-resources/src/main/java/de/unistuttgart/iaas/amyassist/amy/restresources/home/HomeResource.java
- rest-resources/src/test/java/de/unistuttgart/iaas/amyassist/amy/restresources/home/HomeResourceTest.java
Predefined topics. (Minor changes)
The usage of this will be improved later.
> Add predefined topics and change multiple services to use them.

- plugins/example/src/main/java/de/unistuttgart/iaas/amyassist/amy/plugin/example/HelloWorldImpl.java
- plugins/example/src/test/java/de/unistuttgart/iaas/amyassist/amy/plugin/example/HelloWorldTest.java
> improved hello output

- plugins/calendar/src/main/java/de/unistuttgart/iaas/amyassist/amy/plugin/calendar/CalendarLogic.java
- plugins/calendar/src/main/java/de/unistuttgart/iaas/amyassist/amy/plugin/calendar/CalendarService.java
- plugins/calendar/src/test/java/de/unistuttgart/iaas/amyassist/amy/plugin/calendar/CalendarLogicTest.java
Fix setEvent by temporarily deactivating setReccurence() and update Calendar authorisation to read and write.
> Fix Calendar setEvent

- .docker/config/persistence.properties
- Dockerfile
set persistence dir to /data
changed docker image to smaller slim version
> improved Dockerfile

- core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/natlang/NLProcessingManagerImpl.java
- plugins/navigation/src/main/resources/NavigationSpeech.aim.xml
- plugins/spotify/src/main/java/de/unistuttgart/iaas/amyassist/amy/plugin/spotify/SpotifySpeech.java
- plugins/spotify/src/main/resources/SpotifySpeech.aim.xml
some little adjustmnets for speech
> small speech adjustments

- http-server/src/main/java/de/unistuttgart/iaas/amyassist/amy/httpserver/cors/CORSFilter.java
- http-server/src/main/resources/META-INF/cors.config.properties
- http-server/src/test/java/de/unistuttgart/iaas/amyassist/amy/httpserver/cors/CORSFilterTest.java
> Cors improvements

- amy-master-node/pom.xml
> added missing transformer for MessageReceivers

- core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/taskscheduler/TaskSchedulerImpl.java
Fix, that the task scheduler does not stop it's thread at shutdown.
Fixes #429.
> Fix the shutdown of the task scheduler.

- natlang/src/main/java/de/unistuttgart/iaas/amyassist/amy/natlang/PreDefinedEntityTypes.java
- natlang/src/main/java/de/unistuttgart/iaas/amyassist/amy/natlang/languagespecifics/en/EnglishDateTimeUtility.java
- plugins/navigation/src/main/java/de/unistuttgart/iaas/amyassist/amy/plugin/navigation/NavigationSpeech.java
- plugins/navigation/src/main/resources/NavigationSpeech.aim.xml
- plugins/spotify/src/main/resources/SpotifySpeech.aim.xml
now it is possible to say 'now' in the time grammar and the user get the current time. same with today and tomorrow
> Predifend time and date improved

- plugins/spotify/src/main/java/de/unistuttgart/iaas/amyassist/amy/plugin/spotify/SpotifyAPICalls.java
- plugins/spotify/src/main/java/de/unistuttgart/iaas/amyassist/amy/plugin/spotify/SpotifySpeech.java
- plugins/spotify/src/test/java/de/unistuttgart/iaas/amyassist/amy/plugin/spotify/SpotifyAPICallsTest.java
description (is this a bugfix, change or a new feature)
add links to issues
> Resume fix and volume control fix

- natlang/src/main/java/de/unistuttgart/iaas/amyassist/amy/natlang/NLProcessingManagerImpl.java
> bugfix for missing queries in dialogs

- plugins/navigation/src/main/java/de/unistuttgart/iaas/amyassist/amy/plugin/navigation/DirectionApiLogic.java
- plugins/navigation/src/main/resources/NavigationSpeech.aim.xml
> all navigation methods support now the mode bike

- chat-socket/pom.xml
- chat-socket/src/main/java/de/unistuttgart/iaas/amyassist/amy/socket/ChatWebSocket.java
Builds on #427 
Required for AmyAssist/Amy-Web#114
> Chat socket integration

- natlang/src/main/java/de/unistuttgart/iaas/amyassist/amy/natlang/nl/NLLexer.java
- natlang/src/main/java/de/unistuttgart/iaas/amyassist/amy/natlang/userinteraction/UserIntent.java
order of the prompts is now depend now on the order of the entities in the xml. finally all unicode letters are accepted
> Dialog improvement

- plugins/calendar/src/main/java/de/unistuttgart/iaas/amyassist/amy/plugin/calendar/CalendarLogic.java
- plugins/calendar/src/main/java/de/unistuttgart/iaas/amyassist/amy/plugin/calendar/CalendarSpeech.java
- plugins/calendar/src/main/resources/CalendarSpeech.aim.xml
- plugins/calendar/src/test/java/de/unistuttgart/iaas/amyassist/amy/plugin/calendar/CalendarLogicTest.java
Make it possible to create events in the chat and via speech
and add events at functuality (Ask for events on a specific date besides today/tomorrow)
#439 
> Calendar create event speech + ask for events on specific date

- natlang/src/main/java/de/unistuttgart/iaas/amyassist/amy/natlang/PreDefinedEntityTypes.java
> Predefined entites have now a year entitiy

- natlang/src/main/java/de/unistuttgart/iaas/amyassist/amy/natlang/DialogHandlerImpl.java
> Exceptions from Plugins now catched in the dialog handler

- plugins/social/src/main/java/de/unistuttgart/iaas/amyassist/amy/plugin/social/SocialSpeech.java
> fixing currently typo 

- core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/taskscheduler/TaskSchedulerImpl.java
> added logger to TaskScheduler

- plugins/tosca/src/main/java/de/unistuttgart/iaas/amyassist/amy/plugin/tosca/ToscaLogic.java
- plugins/tosca/src/main/java/de/unistuttgart/iaas/amyassist/amy/plugin/tosca/ToscaSpeech.java
- plugins/tosca/src/main/resources/META-INF/de.unistuttgart.iaas.amyassist.amy.core.console.Console
- plugins/tosca/src/main/resources/ToscaSpeech.aim.xml
Included the wait for installation finished
> Tosca wait

- plugins/calendar/src/main/java/de/unistuttgart/iaas/amyassist/amy/plugin/calendar/CalendarSpeech.java
- plugins/calendar/src/main/resources/CalendarSpeech.aim.xml
- plugins/calendar/src/test/java/de/unistuttgart/iaas/amyassist/amy/plugin/calendar/CalendarSpeechTest.java
enhancement of the speech input
> Enhance Calendar conversation

- plugins/social/src/main/java/de/unistuttgart/iaas/amyassist/amy/plugin/social/SocialConstants.java
- plugins/social/src/main/java/de/unistuttgart/iaas/amyassist/amy/plugin/social/SocialLogic.java
- plugins/social/src/main/java/de/unistuttgart/iaas/amyassist/amy/plugin/social/SocialSpeech.java
- plugins/social/src/main/resources/SocialSpeech.aim.xml
> adding social interactions

- plugins/alarmclock/src/main/resources/AlarmclockSpeech.aim.xml
- plugins/spotify/src/main/resources/SpotifySpeech.aim.xml
- plugins/systemtime/src/main/resources/SystemTimeSpeech.aim.xml
- plugins/timer/src/main/resources/TimerSpeech.aim.xml
Check the commands another time and see if they have to be changed.
> Update some commands

- chat-socket/pom.xml
https://nvd.nist.gov/vuln/detail/CVE-2018-7489
> fixed vulnerability in chat-socket

- plugins/mensa/src/main/java/de/unistuttgart/iaas/amyassist/amy/plugin/mensa/MensaLogic.java
The location ID of the cafeteria was changed - this PR reflects this change
This is a bug fix
> Fix Mensa plugin

- amy-message-hub/src/main/java/io/github/amyassist/amy/messagehub/topic/TopicLevelImpl.java
- core/src/main/java/io/github/amyassist/amy/core/audio/environment/LocalAudioEnvironment.java
- core/src/main/java/io/github/amyassist/amy/core/pluginloader/PluginLoader.java
- core/src/main/java/io/github/amyassist/amy/core/speech/tts/AudioInputStreamWithPauseFactory.java
- di/src/main/java/io/github/amyassist/amy/core/di/context/provider/CustomProvider.java
- plugins/timer/src/main/java/io/github/amyassist/amy/plugin/timer/TimerSpeech.java
- plugins/tosca/src/main/java/io/github/amyassist/amy/plugin/tosca/ToscaSpeech.java
- plugins/weather/src/main/java/io/github/amyassist/amy/plugin/weather/WeatherSpeechCommand.java
- registry/src/main/java/io/github/amyassist/amy/registry/LocationRegistryImpl.java
- registry/src/main/java/io/github/amyassist/amy/registry/RegistryException.java
- rest-resources/src/main/java/io/github/amyassist/amy/restresources/chat/ChatResource.java
- rest-resources/src/main/java/io/github/amyassist/amy/restresources/chat/ChatService.java
- testing-framework/src/main/java/io/github/amyassist/amy/test/FrameworkExtension.java
> added some sonarcloud ignores

- remote-sr/src/main/java/io/github/amyassist/amy/remotesr/RemoteSR.java
path in windows format does not match linux style path
> fixed remote-sr chrome profile not parsed on windows

- chat-socket/src/main/java/io/github/amyassist/amy/socket/ChatServer.java
- chat-socket/src/main/java/io/github/amyassist/amy/socket/ChatWebSocket.java
- core/src/main/java/io/github/amyassist/amy/core/Core.java
- http-server/src/main/java/io/github/amyassist/amy/httpserver/ServerImpl.java
> reduced info log output

- plugins/tosca/pom.xml
- plugins/tosca/src/main/java/io/github/amyassist/amy/plugin/tosca/ToscaConsole.java
- plugins/tosca/src/main/java/io/github/amyassist/amy/plugin/tosca/ToscaLibraryAdapter.java
- plugins/tosca/src/main/java/io/github/amyassist/amy/plugin/tosca/ToscaLogic.java
- plugins/tosca/src/main/java/io/github/amyassist/amy/plugin/tosca/ToscaSpeech.java
- plugins/tosca/src/main/resources/META-INF/io.github.amyassist.amy-plugin-tosca.properties
- plugins/tosca/src/test/java/io/github/amyassist/amy/plugin/tosca/ToscaLogicTest.java
updated tests for new model classes
updated configuration file
fix #544
> use the new OpenTOSCA API client 

- .dockerignore
- scripts/systemtest/systemtests.sh
> Fix docker system test job

- .dockerignore
- .travis.yml
- README.md
- amy-master-node/pom.xml
- amy-message-hub/pom.xml
- amy-message-hub/src/main/java/io/github/amyassist/amy/messagehub/internal/SubscriptionObject.java
- chat-socket/pom.xml
- core/src/main/java/io/github/amyassist/amy/core/pluginloader/PluginLoader.java
- core/src/main/java/io/github/amyassist/amy/core/service/RunnableServiceExtension.java
- core/src/test/resources/io/github/amyassist/amy/core/pluginloader/pom.xml
- http-server/pom.xml
- natlang/pom.xml
- persistence/src/main/java/io/github/amyassist/amy/core/persistence/storage/DatabaseStorage.java
- plugins/calendar/pom.xml
- plugins/calendar/src/test/java/io/github/amyassist/amy/plugin/calendar/CalendarRestTest.java
- plugins/webpush/pom.xml
- pom.xml
- rest-resources/pom.xml
- scripts/systemtest/systemtests.sh
- utility/pom.xml
improved:
- improved java 9+ compatibility
- added build step with jdk13
fixed:
- fixed failing integration test
> Release 0.9.0
